language: node_js
node_js:
  - 12
script:
  - npm run build


before_install:
- openssl aes-256-cbc -K $encrypted_f57c64a0b291_key -iv $encrypted_f57c64a0b291_iv
  -in ./travis_deploy_key.enc -out ~/travis_deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ~/travis_deploy_key
- echo -e "Host ipsaone.space\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ~/travis_deploy_key
- ssh -i ~/travis_deploy_key travis@ipsaone.space pwd